name: msra-intern-s-toolkit
dependencies:
  - python=3.8
  - pip:
    - azureml-sdk
    - azure-cli
    - azureml-contrib-aisc
    - --extra-index-url https://azuremlsdktestpypi.azureedge.net/K8s-Compute/D58E86006C65 azureml-contrib-k8s