name: msra-intern-s-toolkit
dependencies:
  - python=3.8
  - pip:
    - azureml-sdk
    - azure-cli
    - azureml-contrib-aisc
    - https://azuremlsdktestpypi.blob.core.windows.net/repo/K8s-Compute/D58E86006C65/azureml_contrib_k8s-0.1.18-py3-none-any.whl?sv=2018-03-28&sr=b&sig=8eejNTpnwccFbmoCf2e0apuApkBgcyLXAh8EmJv0kO8%3D&st=2023-06-26T07%3A36%3A04Z&se=2024-06-26T07%3A36%3A04Z&sp=rl