name: msra-intern-s-toolkit
dependencies:
  - python=3.8
  - pip:
    - azureml-sdk
    - azureml-contrib-aisc
    - "https://azuremlsdktestpypi.blob.core.windows.net/repo/K8s-Compute/D58E86006C65/azureml_contrib_k8s-0.1.18-py3-none-any.whl?sv=2018-03-28&sr=b&sig=OnsZq%2B002V5%2F15N4WRfI9xis18M7rMzLZ4pQYIFIetE%3D&st=2022-06-20T16%3A51%3A01Z&se=2023-06-20T16%3A51%3A01Z&sp=rl"
    